sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t saitejakasala/docker-react .

scripts:
  - docker run saitejakasala/docker-react npm run test -- --watchAll=false
