version: '3'
services: 
  sk_web:
   build:
    context: .
    dockerfile: Dockerfile.dev
   ports:
    - "3000:3000"
   environment: 
    - CHOKIDAR_USEPOLLING=true  
   volumes:
    - /app/node_modules
    - .:/app  
